### ISSUE TITLE
An usefull tool

### ISSUE THREAD

**Issue by AlefAdonis** [mithi/robotics-coursework#10]
The website https://www.tinkercad.com/ is a program that allows you test and make simulations with Arduino that is very cool to train if you dont have one in your hands. I think this is a good insight, mainly for the newbies in robotics.

**Comment by mithi** [comment]
> The website https://www.tinkercad.com/ is a program that allows you test and make simulations with Arduino that is very cool to train if you dont have one in your hands. I think this is a good insight, mainly for the newbies in robotics.

Thanks for submitting this issue. Tinkercad used to be listed here, but I decided that Onshape and Fusion 360 is better for 3d modeling.  It also has very limited functionality when it comes to simulating circuits. But if there is anything else you think should be included here, don't hesitate to submit and issue again!
