### ISSUE TITLE
More about lab equipments

### ISSUE THREAD

**Issue by nhanvu327** [mithi/robotics-coursework#18]
Hi, as a self-learner, I found that what uni students have and I don't is lab experience and it's important in real life. We should collect more articles or resources/instructions about lab activities. @mithi

**Comment by mithi** [comment]
What do you mean lab equipment? 

A lot of courses listed here have create lab exercises, for example:
- https://www.edx.org/course/self-driving-cars-with-duckietown
    - http://duckietown.com/
- https://alliance.seas.upenn.edu/~meam620/wiki/index.php?n=Main.Projects
- https://www.autonomousrobotslab.com/student-projects2.html
- http://prg.cs.umd.edu/enae788m


I'll be closing this issue, we can continue this discussion in https://github.com/mithi/robotics-coursework/issues/17
