### ISSUE TITLE
Few things that need to modify

### ISSUE THREAD

**Issue by Junhyuck-Woo** [mithi/robotics-coursework#19]
I found that some of the courses are not updated, so I leave issues.

- The course is not offered now, and the web-page does not exist.
1. Coursera: Control of Mobile Robots, Magnus Egerstedt, Georgia Institute of technology

- These courses are not offered now.
1. EdX: Robotics: Locomotion Engineering, Dan Koditschek, University of Pennsylvania
2. EdX: Robotics: Dynamics and Control, Vijay Kumar, University of Pennsylvania
3. EdX: Robotics: Vision Intelligence and Machine Learning, Jianbo Shi, University of Pennsylvania
4. EdX: Robotics: Kinematics and Mathematical Foundations, Camillo Taylor, University of Pennsylvania

- The list of robotics courses I knew.
1. Evolutionary robotics course, Josh Bongard, University of Vermont
    https://www.youtube.com/watch?v=CmiJIKxtEOE&list=PLAuiGdPEdw0inlKisMbjDypCbvcb_GBN9
2. Programming for Robotics - ROS, Edo Jelavić, Tom Lankhorst, Marco Hutter, ETHZurich
    https://rsl.ethz.ch/education-students/lectures/ros.html

Thank you for taking the time to read this.

**Comment by mithi** [comment]
> I found that some of the courses are not updated, so I leave issues.
> 
> * The course is not offered now, and the web-page does not exist.
> 
> 1. Coursera: Control of Mobile Robots, Magnus Egerstedt, Georgia Institute of technology
> 
> * These courses are not offered now.
> 
> 1. EdX: Robotics: Locomotion Engineering, Dan Koditschek, University of Pennsylvania
> 2. EdX: Robotics: Dynamics and Control, Vijay Kumar, University of Pennsylvania
> 3. EdX: Robotics: Vision Intelligence and Machine Learning, Jianbo Shi, University of Pennsylvania
> 4. EdX: Robotics: Kinematics and Mathematical Foundations, Camillo Taylor, University of Pennsylvania
> 
> * The list of robotics courses I knew.
> 
> 1. Evolutionary robotics course, Josh Bongard, University of Vermont
>    https://www.youtube.com/watch?v=CmiJIKxtEOE&list=PLAuiGdPEdw0inlKisMbjDypCbvcb_GBN9
> 2. Programming for Robotics - ROS, Edo Jelavić, Tom Lankhorst, Marco Hutter, ETHZurich
>    https://rsl.ethz.ch/education-students/lectures/ros.html
> 
> Thank you for taking the time to read this.

Thanks for the heads up! I'll be updating the readme now. Thanks again!
