### ISSUE TITLE
Pending links

### ISSUE THREAD

**Issue by mithi** [mithi/robotics-coursework#6]
# Youtubers

Will Cogley
https://www.youtube.com/channel/UCkUD_8b1JoTL2ipOVtxfNKw

Angus Devenson from Maker's Muse 
https://www.makersmuse.com/

Michael Laws from Teaching Tech 
https://www.thingiverse.com/TeachingTech/about

James Bruton
https://youtu.be/DfBF26DaT-M

Simone Giertz
http://www.simonegiertz.com/

Naomi Wu
https://www.youtube.com/channel/UCh_ugKacslKhsGGdXP0cRRA

Kris Temmerman
https://www.youtube.com/channel/UCUdunfSS-4CyZsIhICtgr6A

Adam Savage / Tested
 https://www.tested.com/

Michael Reeves
https://www.youtube.com/channel/UCtHaxi4GTYDpJgMSGy7AeSw/channels

Skyentific
https://www.youtube.com/user/SkyentificTube/

Angelo Casimiro
https://www.youtube.com/user/GT10gaming

Ivan Miranda
https://www.youtube.com/user/superazote

ColinFurze
https://www.youtube.com/user/colinfurze/featured

3D printing Nerd
https://www.youtube.com/channel/UC_7aK9PpYTqt08ERh1MewlQ

I tried to explain procedural animation in 10 steps
- https://www.youtube.com/watch?v=e6Gjhr1IP6w

**Comment by mithi** [comment]
# Add favorite projects from instructables, hackster.io etc

**Comment by mithi** [comment]
# Misc
- https://github.com/robz/Linkages3
- https://mechanicaldesign101.com/
- https://dogfeatherdesign.com/engineering-projects/mechanisms-mechanical-walker/
- https://github.com/onlytailei/CppRobotics
- http://grauonline.de/wordpress/?page_id=3244
- https://richardkelley.io/readings
- https://www.mauriciopoppe.com/
- https://diydrones.com

**Comment by mithi** [comment]
# Books on Engineering Dynamics and Machine Design
- Basic Machines and How They Work - Prepared by Bureau of Naval Personnel
- Dynamics, R.C Hibbeler
- Vector Mechanics For Engineers Statics and Dynamics, Ferdinand Beer et al
- Engineering Mechanics Dynamics, J.L, Meriam et al
- Introduction to Statics and Dynamics, Andy Ruina et al
- Engineering Dynamics: A Comprehensive Introduction, Kasdin and Paley
- Fundamentals of Kinematics and Dynamics of Machines and Mechanisms, Oleg Vinogradov
- Machines and mechanism Applied Kinematic Analysis, David H. Myszka
- Design of machinery , Robert Norton
- Mechanisms and Dynamics of Machinery, Hamilton Horth Mabie
-  Mechanisms and Mechanical Devices Sourcebook 2001, Neil Sclater

**Comment by mithi** [comment]
# CAD Tools: Fusion 360 or OnShape? 

- Fusion 360 Tutorial by Lars Christensen
- Fusion 360 Tutorial by Product Design Online
- OnShape Beginner Tutorial - CAD Sessions 
- OnShape Beginner Tutorial - Invent Box Tutorials

**Comment by mithi** [comment]
# Books 

### Jakob Schwichtenberg No Nonsense Book 
- https://nononsensebooks.com/cm/ - Jakob Schwichtenberg

### Think Bayes Allen Downey
- https://github.com/AllenDowney/ThinkBayes2

**Comment by mithi** [comment]
# Books Recommended by @Varun-GP 
- Principles of Robot Motion, Howie Choset
- Modern Robotics: Mechanics, Planning, and Control, Kevin Lynch
- Introduction to Autonomous Mobile Robots, Roland Siegwart
- Planning Algorithms, Steven M. La Valle
- Robot Motion Planning, Jean-Claude Latombe
- Probabilistic Robotics, Sebastian Thrun, Wolfram Burgard, Dieter Fox
- Robotics, Vision and Control, Peter Corke
- Computational Principles of Mobile Robotics, Gregory Dudek, Michael Jenkin

**Comment by mithi** [comment]
# 6.849: Geometric Folding Algorithms: Linkages, Origami, Polyhedra (Spring 2017) Prof. Erik Demaine
http://courses.csail.mit.edu/6.849/spring17/lectures/

# Structure Free , Engineering Dynamics
http://structurefree.blogspot.com/p/engineering-dynamics.html
http://www.engineerstudents.com/engineering-dynamics/

**Comment by mithi** [comment]
# More robotics classes 
- https://alliance.seas.upenn.edu/~meam620/wiki/index.php?n=Main.Pre-requisites

**Comment by mithi** [comment]
# Quadrotor Simulators

- https://github.com/nanicalabs/quadcopter-simulation
- https://github.com/nanicalabs/quadrotor
- https://github.com/nanicalabs/UAV
- https://github.com/nanicalabs/PythonRobotics/tree/master/AerialNavigation/drone_3d_trajectory_following
- https://github.com/nanicalabs/minimum-snap-geometric-control
- https://github.com/nanicalabs/robotics-toolbox-matlab/blob/master/models/mdl_quadrotor.m
- https://github.com/nanicalabs/robotics-toolbox-matlab/blob/master/simulink/quadrotor_dynamics.m

**Comment by mithi** [comment]
# Misc

- https://github.com/robz/Linkages3
- https://mechanicaldesign101.com/
- https://dogfeatherdesign.com/engineering-projects/mechanisms-mechanical-walker/
- https://github.com/onlytailei/CppRobotics
- http://grauonline.de/wordpress/?page_id=3244
- https://richardkelley.io/readings
- https://www.mauriciopoppe.com/
- https://diydrones.com

**Comment by mithi** [comment]
# Open-source quadrupeds

### Spot Micro AI
https://spotmicroai.readthedocs.io/en/latest/

### Stanford Quadruped
https://github.com/stanfordroboticsclub/StanfordQuadruped

### Spot Mini Mini
https://github.com/moribots/spot_mini_mini

**Comment by mithi** [comment]
# Robot Arms Articles 

Gradient Descent Inverse Kinematics for 6DOF robot arms
https://www.marginallyclever.com/2020/04/gradient-descent-inverse-kinematics-for-6dof-robot-arms/

Alan Zucconi
https://www.alanzucconi.com/2017/04/10/robotic-arms/

Robot Arm simulator for the web
https://github.com/glumb/robot-gui
https://github.com/glumb/kinematics

Six Axis Robot arm in unity
https://meuse.co.jp/?p=885
https://meuse.co.jp/?p=2732

Robot kinematics and calibration for arms described by modified dh parameters
https://github.com/nnadeau/pybotics

EvoArm
https://github.com/nanicalabs/EvoArm

Robot arm joint rotations visualizatioon
https://www.youtube.com/watch?v=7coUcEHxnYA
https://www.youtube.com/watch?v=_oL30hxtwPY

3D visualization of the Inverse Kinematic of an industrial robot with 6 degrees of freedom(Kuka)
 RoblabWHGe
https://www.youtube.com/watch?v=3s2x4QsD3uM&t=3s

pseudo inverse jacobian 
 CBlissMath - https://www.youtube.com/watch?v=pTUfUjIQjoE
 Look MA! Studio -https://www.youtube.com/watch?v=HRU1Tlv0GtQ

Jacobian Pseudoinverse 
Damped Least Square
Jacobian Transpose with fixed step size
Jacobian Transpose with varying step size
CCD approaches. 
https://www.youtube.com/watch?v=XdMDuWD8jlk

**Comment by Ly0n** [comment]
Hey,
you missed the AutowareAuto Lecture:
https://www.apex.ai/autoware-course

It a cooperative lecture on ROS2+Autoware.Auto created by multiple companies in the domain of Autonomous Driving and Robotics.

**Comment by mithi** [comment]
> Hey,
> you missed the AutowareAuto Lecture:
> https://www.apex.ai/autoware-course
> 
> It a cooperative lecture on ROS2+Autoware.Auto created by multiple companies in the domain of Autonomous Driving and Robotics.

Hey. This is really cool. Thanks for sharing. I'll go add right away.

**Comment by mithi** [comment]
https://www.omnilink-agents.com/omnisim
https://github.com/omnilink-tech/omnisim
