### ISSUE TITLE
Best platform to learn ROS for beginners??

### ISSUE THREAD

**Issue by tanmayj2020** [mithi/robotics-coursework#9]

**Comment by mithi** [comment]
Hi @tanmayj2020,

I started learning ROS by watching Youtube videos and also reading their official documentation. 
I've tried ROS Ignite Academy free trial by the Construct Sim and it's really good, if you have some money to spare I highly recommend it. https://www.theconstructsim.com/

**Comment by tanmayj2020** [comment]
Thanx for the response . 
I just want to ask is Udacity Nanodegree Robotics beginner friendly course ?? I have read your medium article about it

**Comment by mithi** [comment]
@tanmayj2020 I don't recommend it. It's expensive and not worth the price. If you have some money to spare, I recommend https://www.theconstructsim.com/

**Comment by tanmayj2020** [comment]
Thanx @mithi for replying😁
I’m a college student  working in the field of autonomous mobility. For the past few days, I’ve been following your work and was inspired by your passion in robotics

I’d be highly obliged if we could discuss more about your ongoing research !

**Comment by tanmayj2020** [comment]
Actually TheConstruct is too expensive for our team . We are working for developing a complete state of art self driving car and i am a member of software architecture department.
Are there any other alternatives?

**Comment by bsb808** [comment]
This is a very interesting discussion.  May I ask a clarifying question - when you mention the best "platform" are you referring to

1. The hardware/software foundation such as installing on a host, using docker, using a virtual machine or using the cloud (the Construct framework or [Udacity's virtual desktop](https://engineering.udacity.com/creating-a-gpu-enhanced-virtual-desktop-for-udacity-497bdd91a505) or
2. The actual lessons, tutorials, assignments, etc. to help you learn ROS?

I see these as two separate issues.  I am an instructor and very interested in 1. above.   Ideally three would be an open-source recipe for a virtual environment (Ubuntu + ROS + Gazebo) that folks could use to learn ROS.  

Would anyone be interested in doing some work on 1?  In particular, I'd be interested in seeing if we can reproduce  [Udacity's virtual desktop](https://engineering.udacity.com/creating-a-gpu-enhanced-virtual-desktop-for-udacity-497bdd91a505).  Removing the cost barrier of Udacity or the Construct would be a great educational contribution.

**Comment by tanmayj2020** [comment]
Yes I am interested..
